{"name": "Проверка появления ошибки 403 User already exists при попытке зарегестрировать существующего пользователя", "status": "passed", "steps": [{"name": "Получаю тело запроса для попытки повторной регистрации", "status": "passed", "parameters": [{"name": "email", "value": "'testuser_e9b6859f@ya.com'"}, {"name": "password", "value": "'156710'"}, {"name": "name", "value": "'Laurie Shaw'"}], "start": 1743958739599, "stop": 1743958739599}, {"name": "Регистрация нового пользователя", "status": "passed", "parameters": [{"name": "name", "value": "'Laurie Shaw'"}, {"name": "email", "value": "'testuser_e9b6859f@ya.com'"}, {"name": "password", "value": "'156710'"}], "start": 1743958739599, "stop": 1743958739750}], "start": 1743958739599, "stop": 1743958739751, "uuid": "c76823b7-4c15-42e0-8846-e191d88b5dea", "historyId": "a3b26eb61c4896e6d3cae148673a0df7", "testCaseId": "a3b26eb61c4896e6d3cae148673a0df7", "fullName": "tests.test_user_account_creation.TestReg#test_register_existing_user_returns_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_account_creation"}, {"name": "subSuite", "value": "TestReg"}, {"name": "host", "value": "elishakh"}, {"name": "thread", "value": "18472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_account_creation"}]}